version: "3.9"



services:
  client:
    restart: always
    build:
      context: ./client
    image: messenger-client
    container_name: m-client
    volumes:
      - ./client:/app
    ports:
      - "80:3000"

  nginx:
    image: nginx:1.21.6
    container_name: nginx

  postgres:
    container_name: postgres
    image: postgres:14.2



networks:
  messenger:
    driver: bridge